name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.20.1
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...

